name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        fetch-depth: 1
    - name: Cache libstratosphere debug
      uses: actions/cache@v1
      with:
        path: libstratosphere/debug
        key: libstratosphere-debug
    - name: Cache libstratosphere release
      uses: actions/cache@v1
      with:
        path: libstratosphere/release
        key: libstratosphere-release
    - uses: spacemeowx2/devkitpro-action@v1
      with:
        cmd: make -j8

    - name: Upload built files
      uses: actions/upload-artifact@v1
      with:
        name: sdcard
        path: out/sd
